//get all users data
GET http://localhost:3000/users

//to register user
###
POST http://localhost:3000/register_users
Content-Type: application/json

{
  "name": "example3",
  "email": "example3@gmail.com",
  "phone_number": "1234567890",
  "address": "New york",
  "password": "myPassword",
  "role":""
}

//login
###
POST http://localhost:3000/logIn_users
Content-Type: application/json

{
  "email": "example3@gmail.com",
  "password": "myPassword"
}